z_dim: 5

model: 'cnn'  # 'mlp' or 'cnn'
h_dim: 512  # only used if model='mlp'

# 'normal' for MSE loss, 'bernoulli' for BCE
decoder_dist: bernoulli
lr: 0.005
batch_size: 128

trainer:
  # args for PyTorch Lightning Trainer
  max_epochs: 100
  log_every_n_steps: 50
