# model hyperparameters
hidden_dim: 100
batch_size: 300
lr: 0.001

# utils parameters
split_ratio: 0.05
log_freq_grad: 50
log_freq_histo: 50

# regularization
regularization: L2
weight_decay: 0.009348818325128058
l1_reg: 0.0004765469939154096
dropout: False
batchnorm: False
layernorm: False

# args for PyTorch Lightning Trainer
trainer:
  max_epochs: 1000
  log_every_n_steps: 10